### ISSUE TITLE
I don't understand README

### ISSUE THREAD

**Issue by ghost** [ilyapuchka/Deeper#7]
I have spent 3 hours trying to understand how your library works. I can't get any of my router callbacks to fire. I have attached the project. Could you tell me where I have gone wrong?

I'm sure I have followed your README to the letter.

[WenderCast.zip](https://github.com/ilyapuchka/Deeper/files/1527152/WenderCast.zip)

REF: https://www.raywenderlich.com/156966/push-notifications-tutorial-getting-started

**Comment by ilyapuchka** [comment]
By adding this code to the end of `application:didFinishLaunching:` method the registered callback is called as expected.

```swift
    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
        self.router.open(url: URL(string: "scheme://news/profile")!)
    }
```

In this callback you are checking for `userId` parameter that you didn't define in your route. So this check fails. You can check readme for Deeper module [here](https://github.com/ilyapuchka/Deeper/tree/master/Deeper) or consult with unit tests. There is one typo in the first code snippet in the readme that misses `:` to define a route parameter.

P.S. please next time file an issue that better demonstrates the problem. Even better would be to make a PR with failing test if you discover a bug.
